/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ErrorT,
  ErrorT$inboundSchema,
  ErrorT$Outbound,
  ErrorT$outboundSchema,
} from "./error.js";
import {
  FieldError,
  FieldError$inboundSchema,
  FieldError$Outbound,
  FieldError$outboundSchema,
} from "./fielderror.js";

/**
 * An error has occurred, and further details are contained in the response
 */
export type AccountGetResponseBody = ErrorT | FieldError;

/** @internal */
export const AccountGetResponseBody$inboundSchema: z.ZodType<
  AccountGetResponseBody,
  z.ZodTypeDef,
  unknown
> = z.union([ErrorT$inboundSchema, FieldError$inboundSchema]);

/** @internal */
export type AccountGetResponseBody$Outbound =
  | ErrorT$Outbound
  | FieldError$Outbound;

/** @internal */
export const AccountGetResponseBody$outboundSchema: z.ZodType<
  AccountGetResponseBody$Outbound,
  z.ZodTypeDef,
  AccountGetResponseBody
> = z.union([ErrorT$outboundSchema, FieldError$outboundSchema]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AccountGetResponseBody$ {
  /** @deprecated use `AccountGetResponseBody$inboundSchema` instead. */
  export const inboundSchema = AccountGetResponseBody$inboundSchema;
  /** @deprecated use `AccountGetResponseBody$outboundSchema` instead. */
  export const outboundSchema = AccountGetResponseBody$outboundSchema;
  /** @deprecated use `AccountGetResponseBody$Outbound` instead. */
  export type Outbound = AccountGetResponseBody$Outbound;
}
