/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { ErrorT, ErrorT$inboundSchema, ErrorT$Outbound, ErrorT$outboundSchema } from "./error.js";
import {
    FieldError,
    FieldError$inboundSchema,
    FieldError$Outbound,
    FieldError$outboundSchema,
} from "./fielderror.js";
import * as z from "zod";

/**
 * An error has occurred, and further details are contained in the response
 */
export type PaymentsUpdateResponseBody = ErrorT | FieldError;

/** @internal */
export const PaymentsUpdateResponseBody$inboundSchema: z.ZodType<
    PaymentsUpdateResponseBody,
    z.ZodTypeDef,
    unknown
> = z.union([ErrorT$inboundSchema, FieldError$inboundSchema]);

/** @internal */
export type PaymentsUpdateResponseBody$Outbound = ErrorT$Outbound | FieldError$Outbound;

/** @internal */
export const PaymentsUpdateResponseBody$outboundSchema: z.ZodType<
    PaymentsUpdateResponseBody$Outbound,
    z.ZodTypeDef,
    PaymentsUpdateResponseBody
> = z.union([ErrorT$outboundSchema, FieldError$outboundSchema]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PaymentsUpdateResponseBody$ {
    /** @deprecated use `PaymentsUpdateResponseBody$inboundSchema` instead. */
    export const inboundSchema = PaymentsUpdateResponseBody$inboundSchema;
    /** @deprecated use `PaymentsUpdateResponseBody$outboundSchema` instead. */
    export const outboundSchema = PaymentsUpdateResponseBody$outboundSchema;
    /** @deprecated use `PaymentsUpdateResponseBody$Outbound` instead. */
    export type Outbound = PaymentsUpdateResponseBody$Outbound;
}
