/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ErrorT,
  ErrorT$inboundSchema,
  ErrorT$Outbound,
  ErrorT$outboundSchema,
} from "./error.js";
import {
  FieldError,
  FieldError$inboundSchema,
  FieldError$Outbound,
  FieldError$outboundSchema,
} from "./fielderror.js";

/**
 * An error has occurred, and further details are contained in the response
 */
export type TestingCreditCardGetResponseBody = ErrorT | FieldError;

/** @internal */
export const TestingCreditCardGetResponseBody$inboundSchema: z.ZodType<
  TestingCreditCardGetResponseBody,
  z.ZodTypeDef,
  unknown
> = z.union([ErrorT$inboundSchema, FieldError$inboundSchema]);

/** @internal */
export type TestingCreditCardGetResponseBody$Outbound =
  | ErrorT$Outbound
  | FieldError$Outbound;

/** @internal */
export const TestingCreditCardGetResponseBody$outboundSchema: z.ZodType<
  TestingCreditCardGetResponseBody$Outbound,
  z.ZodTypeDef,
  TestingCreditCardGetResponseBody
> = z.union([ErrorT$outboundSchema, FieldError$outboundSchema]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TestingCreditCardGetResponseBody$ {
  /** @deprecated use `TestingCreditCardGetResponseBody$inboundSchema` instead. */
  export const inboundSchema = TestingCreditCardGetResponseBody$inboundSchema;
  /** @deprecated use `TestingCreditCardGetResponseBody$outboundSchema` instead. */
  export const outboundSchema = TestingCreditCardGetResponseBody$outboundSchema;
  /** @deprecated use `TestingCreditCardGetResponseBody$Outbound` instead. */
  export type Outbound = TestingCreditCardGetResponseBody$Outbound;
}
