/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SDKHooks } from "../hooks/hooks.js";
import { SDKOptions, serverURLFromOptions } from "../lib/config.js";
import {
    encodeBodyForm as encodeBodyForm$,
    encodeSimple as encodeSimple$,
} from "../lib/encodings.js";
import { HTTPClient } from "../lib/http.js";
import * as schemas$ from "../lib/schemas.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as errors from "../models/errors/index.js";
import * as operations from "../models/operations/index.js";

export class OAuth extends ClientSDK {
    private readonly options$: SDKOptions & { hooks?: SDKHooks };

    constructor(options: SDKOptions = {}) {
        const opt = options as unknown;
        let hooks: SDKHooks;
        if (
            typeof opt === "object" &&
            opt != null &&
            "hooks" in opt &&
            opt.hooks instanceof SDKHooks
        ) {
            hooks = opt.hooks;
        } else {
            hooks = new SDKHooks();
        }

        super({
            client: options.httpClient || new HTTPClient(),
            baseURL: serverURLFromOptions(options),
            hooks,
        });

        this.options$ = { ...options, hooks };
        void this.options$;
    }

    /**
     * Get OAuth token
     *
     * @remarks
     * Retrieve a new or refresh an existing OAuth token.
     */
    async getToken(
        xMerchantClientId: string,
        tokenRequest: components.TokenRequest,
        options?: RequestOptions
    ): Promise<operations.OauthGetTokenResponse> {
        const input$: operations.OauthGetTokenRequest = {
            xMerchantClientId: xMerchantClientId,
            tokenRequest: tokenRequest,
        };

        const payload$ = schemas$.parse(
            input$,
            (value$) => operations.OauthGetTokenRequest$outboundSchema.parse(value$),
            "Input validation failed"
        );
        const body$ = Object.entries(payload$["token-request"] || {})
            .map(([k, v]) => {
                return encodeBodyForm$(k, v, { charEncoding: "percent" });
            })
            .join("&");

        const path$ = this.templateURLComponent("/oauth/token")();

        const query$ = "";

        const headers$ = new Headers({
            "Content-Type": "application/x-www-form-urlencoded",
            Accept: "application/json",
            "X-Merchant-Client-Id": encodeSimple$(
                "X-Merchant-Client-Id",
                payload$["X-Merchant-Client-Id"],
                { explode: false, charEncoding: "none" }
            ),
        });

        const context = { operationID: "oauthGetToken", oAuth2Scopes: [], securitySource: null };

        const request$ = this.createRequest$(
            context,
            {
                method: "POST",
                path: path$,
                headers: headers$,
                query: query$,
                body: body$,
                timeoutMs: options?.timeoutMs || this.options$.timeoutMs || -1,
            },
            options
        );

        const response = await this.do$(request$, {
            context,
            errorCodes: ["4XX", "5XX"],
            retryConfig: options?.retries || this.options$.retryConfig,
            retryCodes: options?.retryCodes || ["429", "500", "502", "503", "504"],
        });

        const responseFields$ = {
            ContentType: response.headers.get("content-type") ?? "application/octet-stream",
            StatusCode: response.status,
            RawResponse: response,
            Headers: {},
        };

        const [result$] = await this.matcher<operations.OauthGetTokenResponse>()
            .json(200, operations.OauthGetTokenResponse$inboundSchema, {
                key: "get-access-token-response",
            })
            .json("4XX", errors.OauthGetTokenResponseBody$inboundSchema, { err: true })
            .fail("5XX")
            .void("default", operations.OauthGetTokenResponse$inboundSchema)
            .match(response, { extraFields: responseFields$ });

        return result$;
    }
}
