/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SDK_METADATA, SDKOptions, serverURLFromOptions } from "../lib/config";
import * as enc$ from "../lib/encodings";
import { HTTPClient } from "../lib/http";
import { ClientSDK, RequestOptions } from "../lib/sdks";
import * as components from "../models/components";
import * as errors from "../models/errors";
import * as operations from "../models/operations";

export class Testing extends ClientSDK {
    private readonly options$: SDKOptions;

    constructor(options: SDKOptions = {}) {
        super({
            client: options.httpClient || new HTTPClient(),
            baseURL: serverURLFromOptions(options),
        });

        this.options$ = options;
        void this.options$;
    }

    /**
     * Create a test account
     *
     * @remarks
     * Create a Bolt shopper account for testing purposes.
     *
     */
    async createAccount(
        security: operations.TestingAccountCreateSecurity,
        xPublishableKey: string,
        accountTestCreationData: components.AccountTestCreationData,
        options?: RequestOptions
    ): Promise<operations.TestingAccountCreateResponse> {
        const input$: operations.TestingAccountCreateRequest = {
            xPublishableKey: xPublishableKey,
            accountTestCreationData: accountTestCreationData,
        };
        const headers$ = new Headers();
        headers$.set("user-agent", SDK_METADATA.userAgent);
        headers$.set("Content-Type", "application/json");
        headers$.set("Accept", "application/json");

        const payload$ = operations.TestingAccountCreateRequest$.outboundSchema.parse(input$);

        const body$ = enc$.encodeJSON("body", payload$["account-test-creation-data"], {
            explode: true,
        });

        const path$ = this.templateURLComponent("/testing/accounts")();

        headers$.set(
            "X-Publishable-Key",
            enc$.encodeSimple("X-Publishable-Key", payload$["X-Publishable-Key"], {
                explode: false,
                charEncoding: "none",
            })
        );

        const securitySettings$ = this.resolveSecurity([
            { value: security?.apiKey, fieldName: "X-API-Key", type: "apiKey:header" },
        ]);

        const response = await this.fetch$(
            {
                security: securitySettings$,
                method: "POST",
                path: path$,
                headers: headers$,
                body: body$,
            },
            options
        );

        const responseFields$ = {
            ContentType: response.headers.get("content-type") ?? "application/octet-stream",
            StatusCode: response.status,
            RawResponse: response,
        };

        if (this.matchResponse(response, 200, "application/json")) {
            const responseBody = await response.json();
            const result = operations.TestingAccountCreateResponse$.inboundSchema.parse({
                ...responseFields$,
                "account-test-creation-data": responseBody,
            });
            return result;
        } else if (this.matchResponse(response, "4XX", "application/json")) {
            const responseBody = await response.json();
            const result = errors.TestingAccountCreateResponseBody$.inboundSchema.parse({
                ...responseFields$,
                ...responseBody,
            });
            throw result;
        } else if (this.matchStatusCode(response, "default")) {
            // fallthrough
        } else {
            const responseBody = await response.text();
            throw new errors.SDKError("Unexpected API response", response, responseBody);
        }

        return operations.TestingAccountCreateResponse$.inboundSchema.parse(responseFields$);
    }

    /**
     * Retrieve a test credit card, including its token
     *
     * @remarks
     * Retrieve test credit card information. This includes its token, which can be used to process payments.
     *
     */
    async getCreditCard(
        input: operations.TestingCreditCardGetRequestBody,
        security: operations.TestingCreditCardGetSecurity,
        options?: RequestOptions
    ): Promise<operations.TestingCreditCardGetResponse> {
        const headers$ = new Headers();
        headers$.set("user-agent", SDK_METADATA.userAgent);
        headers$.set("Content-Type", "application/json");
        headers$.set("Accept", "application/json");

        const payload$ = operations.TestingCreditCardGetRequestBody$.outboundSchema.parse(input);
        const body$ = enc$.encodeJSON("body", payload$, { explode: true });

        const path$ = this.templateURLComponent("/testing/credit-cards")();

        const securitySettings$ = this.resolveSecurity([
            { value: security?.apiKey, fieldName: "X-API-Key", type: "apiKey:header" },
        ]);

        const response = await this.fetch$(
            {
                security: securitySettings$,
                method: "POST",
                path: path$,
                headers: headers$,
                body: body$,
            },
            options
        );

        const responseFields$ = {
            ContentType: response.headers.get("content-type") ?? "application/octet-stream",
            StatusCode: response.status,
            RawResponse: response,
        };

        if (this.matchResponse(response, 200, "application/json")) {
            const responseBody = await response.json();
            const result = operations.TestingCreditCardGetResponse$.inboundSchema.parse({
                ...responseFields$,
                "test-credit-card": responseBody,
            });
            return result;
        } else if (this.matchResponse(response, "4XX", "application/json")) {
            const responseBody = await response.json();
            const result = errors.TestingCreditCardGetResponseBody$.inboundSchema.parse({
                ...responseFields$,
                ...responseBody,
            });
            throw result;
        } else if (this.matchStatusCode(response, "default")) {
            // fallthrough
        } else {
            const responseBody = await response.text();
            throw new errors.SDKError("Unexpected API response", response, responseBody);
        }

        return operations.TestingCreditCardGetResponse$.inboundSchema.parse(responseFields$);
    }
}
