workflowVersion: 1.0.0
sources:
    my-source:
        inputs:
            - location: https://api-docs.bolt.com/api.bundle.yaml
targets:
    bolt-typescript:
        target: typescript
        source: my-source
        publish:
            npm:
                token: $NPM_TOKEN
