workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    my-source:
        inputs:
            - location: https://api-docs.bolt.com/api.bundle.yaml
        registry:
            location: registry.speakeasyapi.dev/bolt/boltpublicapi/my-source
targets:
    bolt-typescript:
        target: typescript
        source: my-source
        publish:
            npm:
                token: $NPM_TOKEN
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/bolt/boltpublicapi/my-source-code-samples
            blocking: false
