/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as components from "../../models/components";
import { z } from "zod";

export type AccountExistsRequest = {
    /**
     * A type and value combination that defines the identifier used to detect
     *
     * @remarks
     * the existence of an account.
     *
     */
    identifier: components.Identifier;
    /**
     * The publicly viewable identifier used to identify a merchant division.
     */
    xPublishableKey: string;
};

export type AccountExistsResponse = {
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
};

/** @internal */
export namespace AccountExistsRequest$ {
    export type Inbound = {
        identifier: components.Identifier$.Inbound;
        "X-Publishable-Key": string;
    };

    export const inboundSchema: z.ZodType<AccountExistsRequest, z.ZodTypeDef, Inbound> = z
        .object({
            identifier: components.Identifier$.inboundSchema,
            "X-Publishable-Key": z.string(),
        })
        .transform((v) => {
            return {
                identifier: v.identifier,
                xPublishableKey: v["X-Publishable-Key"],
            };
        });

    export type Outbound = {
        identifier: components.Identifier$.Outbound;
        "X-Publishable-Key": string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, AccountExistsRequest> = z
        .object({
            identifier: components.Identifier$.outboundSchema,
            xPublishableKey: z.string(),
        })
        .transform((v) => {
            return {
                identifier: v.identifier,
                "X-Publishable-Key": v.xPublishableKey,
            };
        });
}

/** @internal */
export namespace AccountExistsResponse$ {
    export type Inbound = {
        ContentType: string;
        StatusCode: number;
        RawResponse: Response;
    };

    export const inboundSchema: z.ZodType<AccountExistsResponse, z.ZodTypeDef, Inbound> = z
        .object({
            ContentType: z.string(),
            StatusCode: z.number().int(),
            RawResponse: z.instanceof(Response),
        })
        .transform((v) => {
            return {
                contentType: v.ContentType,
                statusCode: v.StatusCode,
                rawResponse: v.RawResponse,
            };
        });

    export type Outbound = {
        ContentType: string;
        StatusCode: number;
        RawResponse: never;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, AccountExistsResponse> = z
        .object({
            contentType: z.string(),
            statusCode: z.number().int(),
            rawResponse: z.instanceof(Response).transform(() => {
                throw new Error("Response cannot be serialized");
            }),
        })
        .transform((v) => {
            return {
                ContentType: v.contentType,
                StatusCode: v.statusCode,
                RawResponse: v.rawResponse,
            };
        });
}
