/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { z } from "zod";

export type AccountAddPaymentMethodRequest = {
    /**
     * The publicly viewable identifier used to identify a merchant division.
     */
    xPublishableKey: string;
    requestBody?: any | undefined;
};

export type AccountAddPaymentMethodResponse = {
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
    /**
     * The payment method was successfully added
     */
    paymentMethod?: any | undefined;
};

/** @internal */
export namespace AccountAddPaymentMethodRequest$ {
    export type Inbound = {
        "X-Publishable-Key": string;
        RequestBody?: any | undefined;
    };

    export const inboundSchema: z.ZodType<AccountAddPaymentMethodRequest, z.ZodTypeDef, Inbound> = z
        .object({
            "X-Publishable-Key": z.string(),
            RequestBody: z.any().optional(),
        })
        .transform((v) => {
            return {
                xPublishableKey: v["X-Publishable-Key"],
                ...(v.RequestBody === undefined ? null : { requestBody: v.RequestBody }),
            };
        });

    export type Outbound = {
        "X-Publishable-Key": string;
        RequestBody?: any | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, AccountAddPaymentMethodRequest> =
        z
            .object({
                xPublishableKey: z.string(),
                requestBody: z.any().optional(),
            })
            .transform((v) => {
                return {
                    "X-Publishable-Key": v.xPublishableKey,
                    ...(v.requestBody === undefined ? null : { RequestBody: v.requestBody }),
                };
            });
}

/** @internal */
export namespace AccountAddPaymentMethodResponse$ {
    export type Inbound = {
        ContentType: string;
        StatusCode: number;
        RawResponse: Response;
        "payment-method"?: any | undefined;
    };

    export const inboundSchema: z.ZodType<AccountAddPaymentMethodResponse, z.ZodTypeDef, Inbound> =
        z
            .object({
                ContentType: z.string(),
                StatusCode: z.number().int(),
                RawResponse: z.instanceof(Response),
                "payment-method": z.any().optional(),
            })
            .transform((v) => {
                return {
                    contentType: v.ContentType,
                    statusCode: v.StatusCode,
                    rawResponse: v.RawResponse,
                    ...(v["payment-method"] === undefined
                        ? null
                        : { paymentMethod: v["payment-method"] }),
                };
            });

    export type Outbound = {
        ContentType: string;
        StatusCode: number;
        RawResponse: never;
        "payment-method"?: any | undefined;
    };

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        AccountAddPaymentMethodResponse
    > = z
        .object({
            contentType: z.string(),
            statusCode: z.number().int(),
            rawResponse: z.instanceof(Response).transform(() => {
                throw new Error("Response cannot be serialized");
            }),
            paymentMethod: z.any().optional(),
        })
        .transform((v) => {
            return {
                ContentType: v.contentType,
                StatusCode: v.statusCode,
                RawResponse: v.rawResponse,
                ...(v.paymentMethod === undefined ? null : { "payment-method": v.paymentMethod }),
            };
        });
}
