/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as components from "../components";
import * as z from "zod";

export type AccountAddressCreateRequest = {
    /**
     * The publicly viewable identifier used to identify a merchant division.
     */
    xPublishableKey: string;
    addressListing: components.AddressListingInput;
};

export type AccountAddressCreateResponse = {
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
    /**
     * The address was successfully added
     */
    addressListing?: components.AddressListing | undefined;
};

/** @internal */
export namespace AccountAddressCreateRequest$ {
    export type Inbound = {
        "X-Publishable-Key": string;
        "address-listing": components.AddressListingInput$.Inbound;
    };

    export const inboundSchema: z.ZodType<AccountAddressCreateRequest, z.ZodTypeDef, Inbound> = z
        .object({
            "X-Publishable-Key": z.string(),
            "address-listing": components.AddressListingInput$.inboundSchema,
        })
        .transform((v) => {
            return {
                xPublishableKey: v["X-Publishable-Key"],
                addressListing: v["address-listing"],
            };
        });

    export type Outbound = {
        "X-Publishable-Key": string;
        "address-listing": components.AddressListingInput$.Outbound;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, AccountAddressCreateRequest> = z
        .object({
            xPublishableKey: z.string(),
            addressListing: components.AddressListingInput$.outboundSchema,
        })
        .transform((v) => {
            return {
                "X-Publishable-Key": v.xPublishableKey,
                "address-listing": v.addressListing,
            };
        });
}

/** @internal */
export namespace AccountAddressCreateResponse$ {
    export type Inbound = {
        ContentType: string;
        StatusCode: number;
        RawResponse: Response;
        "address-listing"?: components.AddressListing$.Inbound | undefined;
    };

    export const inboundSchema: z.ZodType<AccountAddressCreateResponse, z.ZodTypeDef, Inbound> = z
        .object({
            ContentType: z.string(),
            StatusCode: z.number().int(),
            RawResponse: z.instanceof(Response),
            "address-listing": components.AddressListing$.inboundSchema.optional(),
        })
        .transform((v) => {
            return {
                contentType: v.ContentType,
                statusCode: v.StatusCode,
                rawResponse: v.RawResponse,
                ...(v["address-listing"] === undefined
                    ? null
                    : { addressListing: v["address-listing"] }),
            };
        });

    export type Outbound = {
        ContentType: string;
        StatusCode: number;
        RawResponse: never;
        "address-listing"?: components.AddressListing$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, AccountAddressCreateResponse> = z
        .object({
            contentType: z.string(),
            statusCode: z.number().int(),
            rawResponse: z.instanceof(Response).transform(() => {
                throw new Error("Response cannot be serialized");
            }),
            addressListing: components.AddressListing$.outboundSchema.optional(),
        })
        .transform((v) => {
            return {
                ContentType: v.contentType,
                StatusCode: v.statusCode,
                RawResponse: v.rawResponse,
                ...(v.addressListing === undefined
                    ? null
                    : { "address-listing": v.addressListing }),
            };
        });
}
