/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { AddressListing, AddressListing$ } from "./addresslisting";
import { Profile, Profile$ } from "./profile";
import { z } from "zod";

export type Account = {
    /**
     * A list of addresses associated with this account.
     */
    addresses: Array<AddressListing>;
    /**
     * A list of payment methods associated with this account.
     */
    paymentMethods: Array<any>;
    profile?: Profile | undefined;
};

/** @internal */
export namespace Account$ {
    export type Inbound = {
        addresses: Array<AddressListing$.Inbound>;
        payment_methods: Array<any>;
        profile?: Profile$.Inbound | undefined;
    };

    export const inboundSchema: z.ZodType<Account, z.ZodTypeDef, Inbound> = z
        .object({
            addresses: z.array(AddressListing$.inboundSchema),
            payment_methods: z.array(z.any()),
            profile: Profile$.inboundSchema.optional(),
        })
        .transform((v) => {
            return {
                addresses: v.addresses,
                paymentMethods: v.payment_methods,
                ...(v.profile === undefined ? null : { profile: v.profile }),
            };
        });

    export type Outbound = {
        addresses: Array<AddressListing$.Outbound>;
        payment_methods: Array<any>;
        profile?: Profile$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, Account> = z
        .object({
            addresses: z.array(AddressListing$.outboundSchema),
            paymentMethods: z.array(z.any()),
            profile: Profile$.outboundSchema.optional(),
        })
        .transform((v) => {
            return {
                addresses: v.addresses,
                payment_methods: v.paymentMethods,
                ...(v.profile === undefined ? null : { profile: v.profile }),
            };
        });
}
