/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import {
    AddressReferenceExplicitInput,
    AddressReferenceExplicitInput$,
    AddressReferenceExplicitTag,
} from "./addressreferenceexplicit.js";
import {
    AddressReferenceId,
    AddressReferenceId$,
    AddressReferenceIdTag,
} from "./addressreferenceid.js";
import * as z from "zod";

export type AddressReferenceInput =
    | (AddressReferenceId & { dotTag: AddressReferenceIdTag.Id })
    | (AddressReferenceExplicitInput & { dotTag: AddressReferenceExplicitTag.Explicit });

/** @internal */
export namespace AddressReferenceInput$ {
    export const inboundSchema: z.ZodType<AddressReferenceInput, z.ZodTypeDef, unknown> = z.union([
        AddressReferenceId$.inboundSchema.and(
            z
                .object({ ".tag": z.literal(AddressReferenceIdTag.Id) })
                .transform((v) => ({ dotTag: v[".tag"] }))
        ),
        AddressReferenceExplicitInput$.inboundSchema.and(
            z
                .object({ ".tag": z.literal(AddressReferenceExplicitTag.Explicit) })
                .transform((v) => ({ dotTag: v[".tag"] }))
        ),
    ]);

    export type Outbound =
        | (AddressReferenceId$.Outbound & { ".tag": AddressReferenceIdTag.Id })
        | (AddressReferenceExplicitInput$.Outbound & {
              ".tag": AddressReferenceExplicitTag.Explicit;
          });
    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, AddressReferenceInput> = z.union(
        [
            AddressReferenceId$.outboundSchema.and(
                z
                    .object({ dotTag: z.literal(AddressReferenceIdTag.Id) })
                    .transform((v) => ({ ".tag": v.dotTag }))
            ),
            AddressReferenceExplicitInput$.outboundSchema.and(
                z
                    .object({ dotTag: z.literal(AddressReferenceExplicitTag.Explicit) })
                    .transform((v) => ({ ".tag": v.dotTag }))
            ),
        ]
    );
}
