/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { Amount, Amount$ } from "./amount";
import { z } from "zod";

export type CartDiscount = {
    /**
     * A monetary amount, i.e. a base unit amount and a supported currency.
     */
    amount: Amount;
    /**
     * Discount code.
     */
    code?: string | undefined;
    /**
     * Used to provide a link to additional details, such as a landing page, associated with the discount offering.
     */
    detailsUrl?: string | undefined;
};

/** @internal */
export namespace CartDiscount$ {
    export type Inbound = {
        amount: Amount$.Inbound;
        code?: string | undefined;
        details_url?: string | undefined;
    };

    export const inboundSchema: z.ZodType<CartDiscount, z.ZodTypeDef, Inbound> = z
        .object({
            amount: Amount$.inboundSchema,
            code: z.string().optional(),
            details_url: z.string().optional(),
        })
        .transform((v) => {
            return {
                amount: v.amount,
                ...(v.code === undefined ? null : { code: v.code }),
                ...(v.details_url === undefined ? null : { detailsUrl: v.details_url }),
            };
        });

    export type Outbound = {
        amount: Amount$.Outbound;
        code?: string | undefined;
        details_url?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, CartDiscount> = z
        .object({
            amount: Amount$.outboundSchema,
            code: z.string().optional(),
            detailsUrl: z.string().optional(),
        })
        .transform((v) => {
            return {
                amount: v.amount,
                ...(v.code === undefined ? null : { code: v.code }),
                ...(v.detailsUrl === undefined ? null : { details_url: v.detailsUrl }),
            };
        });
}
