/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { z } from "zod";

/**
 * The type of OAuth 2.0 grant being utilized. The only supported grant is `authorization_code`.
 */
export enum GrantType {
    AuthorizationCode = "authorization_code",
}

export enum Scope {
    BoltAccountManage = "bolt.account.manage",
    BoltAccountView = "bolt.account.view",
    Openid = "openid",
}

export type GetAccessTokenRequest = {
    /**
     * Fetched value using OTP value from the Authorization Modal.
     */
    code: string;
    /**
     * The OAuth client ID, which corresponds to the merchant publishable key, which can be retrieved
     *
     * @remarks
     * in the Merchant Dashboard.
     *
     */
    clientId: string;
    /**
     * The OAuth client secret, which corresponds the merchant API key, which can be retrieved in the
     *
     * @remarks
     * Merchant Dashboard.
     *
     */
    clientSecret: string;
    /**
     * The type of OAuth 2.0 grant being utilized. The only supported grant is `authorization_code`.
     */
    grantType: GrantType;
    /**
     * The scope issued to the merchant when receiving an authorization code.
     *
     * @remarks
     *
     */
    scope: Array<Scope>;
    /**
     * A randomly generated string sent along with an authorization code. This must be included, if provided,
     *
     * @remarks
     * in order to prevent CSRF attacks. used to prevent CSRF attacks.
     *
     */
    state?: string | undefined;
};

/** @internal */
export const GrantType$ = z.nativeEnum(GrantType);

/** @internal */
export const Scope$ = z.nativeEnum(Scope);

/** @internal */
export namespace GetAccessTokenRequest$ {
    export type Inbound = {
        code: string;
        client_id: string;
        client_secret: string;
        grant_type: GrantType;
        scope: Array<Scope>;
        state?: string | undefined;
    };

    export const inboundSchema: z.ZodType<GetAccessTokenRequest, z.ZodTypeDef, Inbound> = z
        .object({
            code: z.string(),
            client_id: z.string(),
            client_secret: z.string(),
            grant_type: GrantType$,
            scope: z.array(Scope$),
            state: z.string().optional(),
        })
        .transform((v) => {
            return {
                code: v.code,
                clientId: v.client_id,
                clientSecret: v.client_secret,
                grantType: v.grant_type,
                scope: v.scope,
                ...(v.state === undefined ? null : { state: v.state }),
            };
        });

    export type Outbound = {
        code: string;
        client_id: string;
        client_secret: string;
        grant_type: GrantType;
        scope: Array<Scope>;
        state?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetAccessTokenRequest> = z
        .object({
            code: z.string(),
            clientId: z.string(),
            clientSecret: z.string(),
            grantType: GrantType$,
            scope: z.array(Scope$),
            state: z.string().optional(),
        })
        .transform((v) => {
            return {
                code: v.code,
                client_id: v.clientId,
                client_secret: v.clientSecret,
                grant_type: v.grantType,
                scope: v.scope,
                ...(v.state === undefined ? null : { state: v.state }),
            };
        });
}
