/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { Cart, Cart$ } from "./cart";
import { ProfileCreationData, ProfileCreationData$ } from "./profilecreationdata";
import { z } from "zod";

export type GuestPaymentInitializeRequest = {
    profile: ProfileCreationData;
    cart: Cart;
    paymentMethod?: any | undefined;
};

/** @internal */
export namespace GuestPaymentInitializeRequest$ {
    export type Inbound = {
        profile: ProfileCreationData$.Inbound;
        cart: Cart$.Inbound;
        payment_method?: any | undefined;
    };

    export const inboundSchema: z.ZodType<GuestPaymentInitializeRequest, z.ZodTypeDef, Inbound> = z
        .object({
            profile: ProfileCreationData$.inboundSchema,
            cart: Cart$.inboundSchema,
            payment_method: z.any().optional(),
        })
        .transform((v) => {
            return {
                profile: v.profile,
                cart: v.cart,
                ...(v.payment_method === undefined ? null : { paymentMethod: v.payment_method }),
            };
        });

    export type Outbound = {
        profile: ProfileCreationData$.Outbound;
        cart: Cart$.Outbound;
        payment_method?: any | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GuestPaymentInitializeRequest> =
        z
            .object({
                profile: ProfileCreationData$.outboundSchema,
                cart: Cart$.outboundSchema,
                paymentMethod: z.any().optional(),
            })
            .transform((v) => {
                return {
                    profile: v.profile,
                    cart: v.cart,
                    ...(v.paymentMethod === undefined ? null : { payment_method: v.paymentMethod }),
                };
            });
}
