/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export enum PaymentMethodKlarnaAccountTag {
    KlarnaAccount = "klarna_account",
}

export type PaymentMethodKlarnaAccountOutput = {
    dotTag: PaymentMethodKlarnaAccountTag;
};

export type PaymentMethodKlarnaAccount = {
    dotTag: PaymentMethodKlarnaAccountTag;
    /**
     * Return URL to return to after payment completion in Klarna.
     */
    returnUrl: string;
};

/** @internal */
export namespace PaymentMethodKlarnaAccountTag$ {
    export const inboundSchema = z.nativeEnum(PaymentMethodKlarnaAccountTag);
    export const outboundSchema = inboundSchema;
}

/** @internal */
export namespace PaymentMethodKlarnaAccountOutput$ {
    export const inboundSchema: z.ZodType<PaymentMethodKlarnaAccountOutput, z.ZodTypeDef, unknown> =
        z
            .object({
                ".tag": PaymentMethodKlarnaAccountTag$.inboundSchema,
            })
            .transform((v) => {
                return {
                    dotTag: v[".tag"],
                };
            });

    export type Outbound = {
        ".tag": string;
    };

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        PaymentMethodKlarnaAccountOutput
    > = z
        .object({
            dotTag: PaymentMethodKlarnaAccountTag$.outboundSchema,
        })
        .transform((v) => {
            return {
                ".tag": v.dotTag,
            };
        });
}

/** @internal */
export namespace PaymentMethodKlarnaAccount$ {
    export const inboundSchema: z.ZodType<PaymentMethodKlarnaAccount, z.ZodTypeDef, unknown> = z
        .object({
            ".tag": PaymentMethodKlarnaAccountTag$.inboundSchema,
            return_url: z.string(),
        })
        .transform((v) => {
            return {
                dotTag: v[".tag"],
                returnUrl: v.return_url,
            };
        });

    export type Outbound = {
        ".tag": string;
        return_url: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, PaymentMethodKlarnaAccount> = z
        .object({
            dotTag: PaymentMethodKlarnaAccountTag$.outboundSchema,
            returnUrl: z.string(),
        })
        .transform((v) => {
            return {
                ".tag": v.dotTag,
                return_url: v.returnUrl,
            };
        });
}
