/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export enum PaymentResponsePendingTag {
    Pending = "pending",
}

export enum PaymentResponsePendingStatus {
    AwaitingUserConfirmation = "awaiting_user_confirmation",
}

export enum Action {
    Redirect = "redirect",
}

export type PaymentResponsePending = {
    dotTag: PaymentResponsePendingTag;
    id?: string | undefined;
    status: PaymentResponsePendingStatus;
    action: Action;
    url: string;
};

/** @internal */
export const PaymentResponsePendingTag$ = z.nativeEnum(PaymentResponsePendingTag);

/** @internal */
export const PaymentResponsePendingStatus$ = z.nativeEnum(PaymentResponsePendingStatus);

/** @internal */
export const Action$ = z.nativeEnum(Action);

/** @internal */
export namespace PaymentResponsePending$ {
    export type Inbound = {
        ".tag": PaymentResponsePendingTag;
        id?: string | undefined;
        status: PaymentResponsePendingStatus;
        action: Action;
        url: string;
    };

    export const inboundSchema: z.ZodType<PaymentResponsePending, z.ZodTypeDef, Inbound> = z
        .object({
            ".tag": PaymentResponsePendingTag$,
            id: z.string().optional(),
            status: PaymentResponsePendingStatus$,
            action: Action$,
            url: z.string(),
        })
        .transform((v) => {
            return {
                dotTag: v[".tag"],
                ...(v.id === undefined ? null : { id: v.id }),
                status: v.status,
                action: v.action,
                url: v.url,
            };
        });

    export type Outbound = {
        ".tag": PaymentResponsePendingTag;
        id?: string | undefined;
        status: PaymentResponsePendingStatus;
        action: Action;
        url: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, PaymentResponsePending> = z
        .object({
            dotTag: PaymentResponsePendingTag$,
            id: z.string().optional(),
            status: PaymentResponsePendingStatus$,
            action: Action$,
            url: z.string(),
        })
        .transform((v) => {
            return {
                ".tag": v.dotTag,
                ...(v.id === undefined ? null : { id: v.id }),
                status: v.status,
                action: v.action,
                url: v.url,
            };
        });
}
