/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as z from "zod";

export enum PaymentMethodKlarnaTag {
    Klarna = "klarna",
}

export type PaymentMethodKlarnaOutput = {
    dotTag: PaymentMethodKlarnaTag;
};

export type PaymentMethodKlarna = {
    dotTag: PaymentMethodKlarnaTag;
    /**
     * Return URL to return to after payment completion in Klarna.
     */
    returnUrl: string;
};

/** @internal */
export namespace PaymentMethodKlarnaTag$ {
    export const inboundSchema: z.ZodNativeEnum<typeof PaymentMethodKlarnaTag> =
        z.nativeEnum(PaymentMethodKlarnaTag);
    export const outboundSchema: z.ZodNativeEnum<typeof PaymentMethodKlarnaTag> = inboundSchema;
}

/** @internal */
export namespace PaymentMethodKlarnaOutput$ {
    export const inboundSchema: z.ZodType<PaymentMethodKlarnaOutput, z.ZodTypeDef, unknown> = z
        .object({
            ".tag": PaymentMethodKlarnaTag$.inboundSchema,
        })
        .transform((v) => {
            return remap$(v, {
                ".tag": "dotTag",
            });
        });

    export type Outbound = {
        ".tag": string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, PaymentMethodKlarnaOutput> = z
        .object({
            dotTag: PaymentMethodKlarnaTag$.outboundSchema,
        })
        .transform((v) => {
            return remap$(v, {
                dotTag: ".tag",
            });
        });
}

/** @internal */
export namespace PaymentMethodKlarna$ {
    export const inboundSchema: z.ZodType<PaymentMethodKlarna, z.ZodTypeDef, unknown> = z
        .object({
            ".tag": PaymentMethodKlarnaTag$.inboundSchema,
            return_url: z.string(),
        })
        .transform((v) => {
            return remap$(v, {
                ".tag": "dotTag",
                return_url: "returnUrl",
            });
        });

    export type Outbound = {
        ".tag": string;
        return_url: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, PaymentMethodKlarna> = z
        .object({
            dotTag: PaymentMethodKlarnaTag$.outboundSchema,
            returnUrl: z.string(),
        })
        .transform((v) => {
            return remap$(v, {
                dotTag: ".tag",
                returnUrl: "return_url",
            });
        });
}
