/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as z from "zod";

export enum PaymentMethodKlarnaPaynowTag {
    KlarnaPaynow = "klarna_paynow",
}

export type PaymentMethodKlarnaPaynowOutput = {
    dotTag: PaymentMethodKlarnaPaynowTag;
};

export type PaymentMethodKlarnaPaynow = {
    dotTag: PaymentMethodKlarnaPaynowTag;
    /**
     * Return URL to return to after payment completion in Klarna.
     */
    returnUrl: string;
};

/** @internal */
export namespace PaymentMethodKlarnaPaynowTag$ {
    export const inboundSchema: z.ZodNativeEnum<typeof PaymentMethodKlarnaPaynowTag> = z.nativeEnum(
        PaymentMethodKlarnaPaynowTag
    );
    export const outboundSchema: z.ZodNativeEnum<typeof PaymentMethodKlarnaPaynowTag> =
        inboundSchema;
}

/** @internal */
export namespace PaymentMethodKlarnaPaynowOutput$ {
    export const inboundSchema: z.ZodType<PaymentMethodKlarnaPaynowOutput, z.ZodTypeDef, unknown> =
        z
            .object({
                ".tag": PaymentMethodKlarnaPaynowTag$.inboundSchema,
            })
            .transform((v) => {
                return remap$(v, {
                    ".tag": "dotTag",
                });
            });

    export type Outbound = {
        ".tag": string;
    };

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        PaymentMethodKlarnaPaynowOutput
    > = z
        .object({
            dotTag: PaymentMethodKlarnaPaynowTag$.outboundSchema,
        })
        .transform((v) => {
            return remap$(v, {
                dotTag: ".tag",
            });
        });
}

/** @internal */
export namespace PaymentMethodKlarnaPaynow$ {
    export const inboundSchema: z.ZodType<PaymentMethodKlarnaPaynow, z.ZodTypeDef, unknown> = z
        .object({
            ".tag": PaymentMethodKlarnaPaynowTag$.inboundSchema,
            return_url: z.string(),
        })
        .transform((v) => {
            return remap$(v, {
                ".tag": "dotTag",
                return_url: "returnUrl",
            });
        });

    export type Outbound = {
        ".tag": string;
        return_url: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, PaymentMethodKlarnaPaynow> = z
        .object({
            dotTag: PaymentMethodKlarnaPaynowTag$.outboundSchema,
            returnUrl: z.string(),
        })
        .transform((v) => {
            return remap$(v, {
                dotTag: ".tag",
                returnUrl: "return_url",
            });
        });
}
