/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { Transaction, Transaction$ } from "./transaction";
import * as z from "zod";

export enum PaymentResponseFinalizedTag {
    Finalized = "finalized",
}

export enum Status {
    Success = "success",
}

export type PaymentResponseFinalized = {
    dotTag: PaymentResponseFinalizedTag;
    id?: string | undefined;
    status: Status;
    transaction: Transaction;
};

/** @internal */
export namespace PaymentResponseFinalizedTag$ {
    export const inboundSchema = z.nativeEnum(PaymentResponseFinalizedTag);
    export const outboundSchema = inboundSchema;
}

/** @internal */
export namespace Status$ {
    export const inboundSchema = z.nativeEnum(Status);
    export const outboundSchema = inboundSchema;
}

/** @internal */
export namespace PaymentResponseFinalized$ {
    export const inboundSchema: z.ZodType<PaymentResponseFinalized, z.ZodTypeDef, unknown> = z
        .object({
            ".tag": PaymentResponseFinalizedTag$.inboundSchema,
            id: z.string().optional(),
            status: Status$.inboundSchema,
            transaction: Transaction$.inboundSchema,
        })
        .transform((v) => {
            return {
                dotTag: v[".tag"],
                ...(v.id === undefined ? null : { id: v.id }),
                status: v.status,
                transaction: v.transaction,
            };
        });

    export type Outbound = {
        ".tag": string;
        id?: string | undefined;
        status: string;
        transaction: Transaction$.Outbound;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, PaymentResponseFinalized> = z
        .object({
            dotTag: PaymentResponseFinalizedTag$.outboundSchema,
            id: z.string().optional(),
            status: Status$.outboundSchema,
            transaction: Transaction$.outboundSchema,
        })
        .transform((v) => {
            return {
                ".tag": v.dotTag,
                ...(v.id === undefined ? null : { id: v.id }),
                status: v.status,
                transaction: v.transaction,
            };
        });
}
