/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import {
    PaymentMethodAffirm,
    PaymentMethodAffirm$,
    PaymentMethodAffirmTag,
} from "./paymentmethodaffirmoutput";
import {
    PaymentMethodAfterpay,
    PaymentMethodAfterpay$,
    PaymentMethodAfterpayTag,
} from "./paymentmethodafterpayoutput";
import {
    DotTag,
    PaymentMethodCreditCardInput,
    PaymentMethodCreditCardInput$,
} from "./paymentmethodcreditcard";
import {
    PaymentMethodKlarnaAccount,
    PaymentMethodKlarnaAccount$,
    PaymentMethodKlarnaAccountTag,
} from "./paymentmethodklarnaaccountoutput";
import {
    PaymentMethodKlarna,
    PaymentMethodKlarna$,
    PaymentMethodKlarnaTag,
} from "./paymentmethodklarnaoutput";
import {
    PaymentMethodKlarnaPaynow,
    PaymentMethodKlarnaPaynow$,
    PaymentMethodKlarnaPaynowTag,
} from "./paymentmethodklarnapaynowoutput";
import {
    PaymentMethodPaypal,
    PaymentMethodPaypal$,
    PaymentMethodPaypalTag,
} from "./paymentmethodpaypaloutput";
import {
    PaymentMethodReference,
    PaymentMethodReference$,
    PaymentMethodReferenceTag,
} from "./paymentmethodreference";
import * as z from "zod";

export type PaymentMethodExtended =
    | (PaymentMethodReference & { dotTag: PaymentMethodReferenceTag.Id })
    | (PaymentMethodAffirm & { dotTag: PaymentMethodAffirmTag.Affirm })
    | (PaymentMethodAfterpay & { dotTag: PaymentMethodAfterpayTag.Afterpay })
    | (PaymentMethodKlarna & { dotTag: PaymentMethodKlarnaTag.Klarna })
    | (PaymentMethodKlarnaAccount & { dotTag: PaymentMethodKlarnaAccountTag.KlarnaAccount })
    | (PaymentMethodKlarnaPaynow & { dotTag: PaymentMethodKlarnaPaynowTag.KlarnaPaynow })
    | (PaymentMethodPaypal & { dotTag: PaymentMethodPaypalTag.Paypal })
    | (PaymentMethodCreditCardInput & { dotTag: DotTag.CreditCard });

/** @internal */
export namespace PaymentMethodExtended$ {
    export const inboundSchema: z.ZodType<PaymentMethodExtended, z.ZodTypeDef, unknown> = z.union([
        PaymentMethodReference$.inboundSchema.and(
            z
                .object({ ".tag": z.literal(PaymentMethodReferenceTag.Id) })
                .transform((v) => ({ dotTag: v[".tag"] }))
        ),
        PaymentMethodAffirm$.inboundSchema.and(
            z
                .object({ ".tag": z.literal(PaymentMethodAffirmTag.Affirm) })
                .transform((v) => ({ dotTag: v[".tag"] }))
        ),
        PaymentMethodAfterpay$.inboundSchema.and(
            z
                .object({ ".tag": z.literal(PaymentMethodAfterpayTag.Afterpay) })
                .transform((v) => ({ dotTag: v[".tag"] }))
        ),
        PaymentMethodKlarna$.inboundSchema.and(
            z
                .object({ ".tag": z.literal(PaymentMethodKlarnaTag.Klarna) })
                .transform((v) => ({ dotTag: v[".tag"] }))
        ),
        PaymentMethodKlarnaAccount$.inboundSchema.and(
            z
                .object({ ".tag": z.literal(PaymentMethodKlarnaAccountTag.KlarnaAccount) })
                .transform((v) => ({ dotTag: v[".tag"] }))
        ),
        PaymentMethodKlarnaPaynow$.inboundSchema.and(
            z
                .object({ ".tag": z.literal(PaymentMethodKlarnaPaynowTag.KlarnaPaynow) })
                .transform((v) => ({ dotTag: v[".tag"] }))
        ),
        PaymentMethodPaypal$.inboundSchema.and(
            z
                .object({ ".tag": z.literal(PaymentMethodPaypalTag.Paypal) })
                .transform((v) => ({ dotTag: v[".tag"] }))
        ),
        PaymentMethodCreditCardInput$.inboundSchema.and(
            z
                .object({ ".tag": z.literal(DotTag.CreditCard) })
                .transform((v) => ({ dotTag: v[".tag"] }))
        ),
    ]);

    export type Outbound =
        | (PaymentMethodReference$.Outbound & { ".tag": PaymentMethodReferenceTag.Id })
        | (PaymentMethodAffirm$.Outbound & { ".tag": PaymentMethodAffirmTag.Affirm })
        | (PaymentMethodAfterpay$.Outbound & { ".tag": PaymentMethodAfterpayTag.Afterpay })
        | (PaymentMethodKlarna$.Outbound & { ".tag": PaymentMethodKlarnaTag.Klarna })
        | (PaymentMethodKlarnaAccount$.Outbound & {
              ".tag": PaymentMethodKlarnaAccountTag.KlarnaAccount;
          })
        | (PaymentMethodKlarnaPaynow$.Outbound & {
              ".tag": PaymentMethodKlarnaPaynowTag.KlarnaPaynow;
          })
        | (PaymentMethodPaypal$.Outbound & { ".tag": PaymentMethodPaypalTag.Paypal })
        | (PaymentMethodCreditCardInput$.Outbound & { ".tag": DotTag.CreditCard });
    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, PaymentMethodExtended> = z.union(
        [
            PaymentMethodReference$.outboundSchema.and(
                z
                    .object({ dotTag: z.literal(PaymentMethodReferenceTag.Id) })
                    .transform((v) => ({ ".tag": v.dotTag }))
            ),
            PaymentMethodAffirm$.outboundSchema.and(
                z
                    .object({ dotTag: z.literal(PaymentMethodAffirmTag.Affirm) })
                    .transform((v) => ({ ".tag": v.dotTag }))
            ),
            PaymentMethodAfterpay$.outboundSchema.and(
                z
                    .object({ dotTag: z.literal(PaymentMethodAfterpayTag.Afterpay) })
                    .transform((v) => ({ ".tag": v.dotTag }))
            ),
            PaymentMethodKlarna$.outboundSchema.and(
                z
                    .object({ dotTag: z.literal(PaymentMethodKlarnaTag.Klarna) })
                    .transform((v) => ({ ".tag": v.dotTag }))
            ),
            PaymentMethodKlarnaAccount$.outboundSchema.and(
                z
                    .object({ dotTag: z.literal(PaymentMethodKlarnaAccountTag.KlarnaAccount) })
                    .transform((v) => ({ ".tag": v.dotTag }))
            ),
            PaymentMethodKlarnaPaynow$.outboundSchema.and(
                z
                    .object({ dotTag: z.literal(PaymentMethodKlarnaPaynowTag.KlarnaPaynow) })
                    .transform((v) => ({ ".tag": v.dotTag }))
            ),
            PaymentMethodPaypal$.outboundSchema.and(
                z
                    .object({ dotTag: z.literal(PaymentMethodPaypalTag.Paypal) })
                    .transform((v) => ({ ".tag": v.dotTag }))
            ),
            PaymentMethodCreditCardInput$.outboundSchema.and(
                z
                    .object({ dotTag: z.literal(DotTag.CreditCard) })
                    .transform((v) => ({ ".tag": v.dotTag }))
            ),
        ]
    );
}
