/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export enum PaymentMethodAffirmTag {
    Affirm = "affirm",
}

export type PaymentMethodAffirmOutput = {
    dotTag: PaymentMethodAffirmTag;
};

export type PaymentMethodAffirm = {
    dotTag: PaymentMethodAffirmTag;
    /**
     * Return URL to return to after payment completion in Affirm.
     */
    returnUrl: string;
};

/** @internal */
export namespace PaymentMethodAffirmTag$ {
    export const inboundSchema = z.nativeEnum(PaymentMethodAffirmTag);
    export const outboundSchema = inboundSchema;
}

/** @internal */
export namespace PaymentMethodAffirmOutput$ {
    export const inboundSchema: z.ZodType<PaymentMethodAffirmOutput, z.ZodTypeDef, unknown> = z
        .object({
            ".tag": PaymentMethodAffirmTag$.inboundSchema,
        })
        .transform((v) => {
            return {
                dotTag: v[".tag"],
            };
        });

    export type Outbound = {
        ".tag": string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, PaymentMethodAffirmOutput> = z
        .object({
            dotTag: PaymentMethodAffirmTag$.outboundSchema,
        })
        .transform((v) => {
            return {
                ".tag": v.dotTag,
            };
        });
}

/** @internal */
export namespace PaymentMethodAffirm$ {
    export const inboundSchema: z.ZodType<PaymentMethodAffirm, z.ZodTypeDef, unknown> = z
        .object({
            ".tag": PaymentMethodAffirmTag$.inboundSchema,
            return_url: z.string(),
        })
        .transform((v) => {
            return {
                dotTag: v[".tag"],
                returnUrl: v.return_url,
            };
        });

    export type Outbound = {
        ".tag": string;
        return_url: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, PaymentMethodAffirm> = z
        .object({
            dotTag: PaymentMethodAffirmTag$.outboundSchema,
            returnUrl: z.string(),
        })
        .transform((v) => {
            return {
                ".tag": v.dotTag,
                return_url: v.returnUrl,
            };
        });
}
