/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * The type of OAuth 2.0 grant being utilized.
 */
export enum RefreshTokenRequestGrantType {
    RefreshToken = "refresh_token",
}

export enum RefreshTokenRequestScope {
    BoltAccountManage = "bolt.account.manage",
    BoltAccountView = "bolt.account.view",
    Openid = "openid",
}

export type RefreshTokenRequest = {
    /**
     * The type of OAuth 2.0 grant being utilized.
     */
    grantType: RefreshTokenRequestGrantType;
    /**
     * The value of the refresh token issued to you in the originating OAuth token request.
     */
    refreshToken: string;
    /**
     * The OAuth client ID, which corresponds to the merchant publishable key, which can be retrieved
     *
     * @remarks
     * in the Merchant Dashboard.
     *
     */
    clientId: string;
    /**
     * The OAuth client secret, which corresponds the merchant API key, which can be retrieved in the
     *
     * @remarks
     * Merchant Dashboard.
     *
     */
    clientSecret: string;
    /**
     * The requested scopes. If the request is successful, the OAuth client will be able to perform operations requiring these scopes.
     *
     * @remarks
     *
     */
    scope: Array<RefreshTokenRequestScope>;
    /**
     * A randomly generated string sent along with an authorization code. This must be included, if provided,
     *
     * @remarks
     * in order to prevent CSRF attacks. used to prevent CSRF attacks.
     *
     */
    state?: string | undefined;
};

/** @internal */
export const RefreshTokenRequestGrantType$: z.ZodNativeEnum<typeof RefreshTokenRequestGrantType> =
    z.nativeEnum(RefreshTokenRequestGrantType);

/** @internal */
export const RefreshTokenRequestScope$: z.ZodNativeEnum<typeof RefreshTokenRequestScope> =
    z.nativeEnum(RefreshTokenRequestScope);

/** @internal */
export namespace RefreshTokenRequest$ {
    export const inboundSchema: z.ZodType<RefreshTokenRequest, z.ZodTypeDef, unknown> = z
        .object({
            grant_type: RefreshTokenRequestGrantType$,
            refresh_token: z.string(),
            client_id: z.string(),
            client_secret: z.string(),
            scope: z.array(RefreshTokenRequestScope$),
            state: z.string().optional(),
        })
        .transform((v) => {
            return {
                grantType: v.grant_type,
                refreshToken: v.refresh_token,
                clientId: v.client_id,
                clientSecret: v.client_secret,
                scope: v.scope,
                ...(v.state === undefined ? null : { state: v.state }),
            };
        });

    export type Outbound = {
        grant_type: RefreshTokenRequestGrantType;
        refresh_token: string;
        client_id: string;
        client_secret: string;
        scope: Array<RefreshTokenRequestScope>;
        state?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, RefreshTokenRequest> = z
        .object({
            grantType: RefreshTokenRequestGrantType$,
            refreshToken: z.string(),
            clientId: z.string(),
            clientSecret: z.string(),
            scope: z.array(RefreshTokenRequestScope$),
            state: z.string().optional(),
        })
        .transform((v) => {
            return {
                grant_type: v.grantType,
                refresh_token: v.refreshToken,
                client_id: v.clientId,
                client_secret: v.clientSecret,
                scope: v.scope,
                ...(v.state === undefined ? null : { state: v.state }),
            };
        });
}
