/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../internal/utils";
import { Expose, Transform } from "class-transformer";

/**
 * The credit card's network.
 */
export enum Network {
    Visa = "visa",
    Mastercard = "mastercard",
    Amex = "amex",
    Discover = "discover",
    Jcb = "jcb",
    Unionpay = "unionpay",
    Alliancedata = "alliancedata",
    Citiplcc = "citiplcc",
}

export class TestCreditCard extends SpeakeasyBase {
    /**
     * The credit card's network.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "network" })
    network: Network;

    /**
     * The Bank Identification Number (BIN). This is typically the first 4 to 6 digits of the account number.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "bin" })
    bin: string;

    /**
     * The account number's last four digits.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "last4" })
    last4: string;

    /**
     * The token's expiration date. Tokens used past their expiration will be rejected.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "expiration" })
    @Transform(({ value }) => new Date(value), { toClassOnly: true })
    expiration: Date;

    /**
     * The Bolt token associated with the credit card.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "token" })
    token: string;
}
